**Homework 1** - Completed by [Mahesh Kumaar Balaji](mbalaji@scu.edu).

In [1]:
import numpy as np # type: ignore

a = np.array([3, 1, 5, 6, 2, 0])
b = np.array([6, 4, -1])
c = np.array([2, 4, 3, 6, -1, 2])
d = np.array([5, 2, 3, 1])
e = np.array([3, -2, 1, 4])
f = np.array([2, 1, 3, 5, 7, -2])

In [2]:
print('Initializing matrices')
a = a.reshape(2, 3)
print('A = ', a)

b = b.reshape(3, 1)
print('B = ', b)

c = c.reshape(3, 2)
print('C = ', c)

d = d.reshape(2, 2)
print('D = ', d)

e = e.reshape(2, 2)
print('E = ', e)

f = f.reshape(2, 3)
print('F = ', f)

print('')

Initializing matrices
A =  [[3 1 5]
 [6 2 0]]
B =  [[ 6]
 [ 4]
 [-1]]
C =  [[ 2  4]
 [ 3  6]
 [-1  2]]
D =  [[5 2]
 [3 1]]
E =  [[ 3 -2]
 [ 1  4]]
F =  [[ 2  1  3]
 [ 5  7 -2]]



In [3]:
print('Question - 1')
if a.shape == f.shape:
    aplusf = a + f
    print('A + F = ', aplusf)
else:
    print('A + F = Invalid')

print('')

Question - 1
A + F =  [[ 5  2  8]
 [11  9 -2]]



In [4]:
print('Question - 2')
if e.shape == d.shape:
    eminusd = e - d
    print('E - D = ', eminusd)
else:
    print('E - D = Invalid')

print('')

Question - 2
E - D =  [[-2 -4]
 [-2  3]]



In [5]:
print('Question - 3')
if c.shape == b.shape:
    cplusb = c + b
    print('C + B = ', cplusb)
else:
    print('C + B = Invalid')

print('')

Question - 3
C + B = Invalid



In [6]:
print('Question - 4')
(c_row, c_col) = c.shape
(d_row, d_col) = d.shape
if c_col == d_row:
    cintod = np.dot(c, d)
    print('C(D) = ', cintod)
else:
    print('C(D) = Invalid')

print('')

Question - 4
C(D) =  [[22  8]
 [33 12]
 [ 1  0]]



In [7]:
print('Question - 5')
(a_row, a_col) = a.shape
(f_row, f_col) = f.shape
if a_col == f_row:
    aintof = np.dot(a, f)
    print('A(F) = ', aintof)
else:
    print('A(F) = Invalid')

print('')

Question - 5
A(F) = Invalid



In [8]:
print('Question - 6')
ct = c.transpose()
print('C^T = ', ct)

print('')

Question - 6
C^T =  [[ 2  3 -1]
 [ 4  6  2]]



In [9]:
print('Question - 7')
ft = f.transpose()
(ft_row, ft_col) = ft.shape
(e_row, e_col) = e.shape
if ft_col == e_row:
    ftintoe = np.dot(ft, e)
    print('F^T(E) = ', ftintoe)
else:
    print('F^T(E) = Invalid')

Question - 7
F^T(E) =  [[ 11  16]
 [ 10  26]
 [  7 -14]]
